apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: {{ .Values.namespace }}

data:
  index.html: |
{{ .Files.Get "web-content/index.html" | indent 4 }}

  style.css: |
{{ .Files.Get "web-content/style.css" | indent 4 }}
