apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webapp-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "webapp-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "webapp-chart.name" . }}
    spec:
      serviceAccountName: {{ include "webapp-chart.fullname" . }}
      containers:
        - name: webapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              value: {{ .Values.config.environment }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
