apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  db-name: {{ .Values.secrets.db.name }}
  db-user: {{ .Values.secrets.db.user }}
  db-password: {{ .Values.secrets.db.password }}
