namespace: pre

environment: pre

frontend:
  replicaCount: 1

  image:
    repository: nginx
    tag: stable

  host: pre.demo.local

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"

    limits:
      cpu: "250m"
      memory: "256Mi"

backend:
  replicaCount: 1

  image:
    repository: node
    tag: 20-alpine

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"

    limits:
      cpu: "250m"
      memory: "256Mi"

  autoscaling:
    enabled: false

database:
  image:
    repository: postgres
    tag: "16"

  storage: 2Gi

secrets:
  db:
    name: appdb
    user: preuser
    password: pass
